"""Hinge (linear-in-V C) Coss/Crss model: accuracy, physicality, and its refusals.

The guards here are calibrated against constructed KNOWN-BAD inputs, not only against good
ones: a non-monotone curve and an under-resolved knot budget must both make the emitter FAIL.
A guard never observed to fire is not evidence of anything.
"""

from __future__ import annotations

import re

import numpy as np
import pytest

from datasheet_chart_digitizer.coss_export import (
    build_adaptive_hinge_model,
    evaluate_hinge_model,
    hinge_charge_expression,
    hinge_charge_terms,
    spice_hinge_charge,
)


def _junction_curve(n=600, vmax=100.0, cjo=3000.0, vj=2.0, m=0.55):
    """A realistic monotone junction-like C(V): steep knee, long flat tail."""
    v = np.linspace(0.0, vmax, n)
    return v, cjo / (1.0 + v / vj) ** m


def test_meets_target_and_is_monotone_on_a_realistic_curve():
    v, c = _junction_curve()
    model = build_adaptive_hinge_model(v, c, max_rel_error=0.02)

    assert model.meets_target
    assert model.monotone
    assert model.achieved_max_rel_error <= 0.02
    # the point of the adaptive form: a 20x dynamic range in a handful of knots
    assert len(model.vds) < 40, f"unexpectedly many knots: {len(model.vds)}"

    pred = evaluate_hinge_model(model, v)
    assert np.max(np.abs(pred / c - 1.0)) <= 0.02


def test_tighter_target_costs_knots_but_still_converges():
    v, c = _junction_curve()
    loose = build_adaptive_hinge_model(v, c, max_rel_error=0.02)
    tight = build_adaptive_hinge_model(v, c, max_rel_error=0.005)

    assert tight.achieved_max_rel_error < loose.achieved_max_rel_error
    assert len(tight.vds) > len(loose.vds)
    assert tight.meets_target


def test_charge_expression_differentiates_back_to_the_modelled_capacitance():
    """Q must be the exact integral of the SAME C the model evaluates -- one curve, not two."""
    v, c = _junction_curve()
    model = build_adaptive_hinge_model(v, c, max_rel_error=0.02)
    expr = hinge_charge_expression(model)

    def q_of(x):
        # SAFETY: `expr` is generated by hinge_charge_expression from numeric knots in this
        # same test -- it is never user or file input. Builtins are stripped and only the three
        # math callables the emitter can produce are exposed. Evaluating it is the POINT of the
        # test: it checks the emitted SPICE text itself, so parsing it with anything other than
        # the arithmetic it denotes would test a different artifact than the one shipped.
        ns = {"min": min, "max": max, "pow": pow, "x": float(x)}
        return eval(expr, {"__builtins__": {}}, ns)  # noqa: S307

    # sample away from knots so the central difference does not straddle a slope kink
    kv = set(np.round(model.vds, 6))
    probes = [x for x in np.linspace(1.0, 99.0, 97) if round(x, 6) not in kv]
    h = 1e-4
    got = np.array([(q_of(x + h) - q_of(x - h)) / (2 * h) for x in probes]) * 1e12
    want = evaluate_hinge_model(model, np.array(probes))
    assert np.allclose(got, want, rtol=2e-3), np.max(np.abs(got / want - 1))


def test_tails_are_flat_outside_the_knot_range_not_extrapolated():
    """The loss deck swings below 0 V and rings above the top knot; a continued last slope
    would drive C negative there."""
    v, c = _junction_curve()
    model = build_adaptive_hinge_model(v, c, max_rel_error=0.02)

    below = evaluate_hinge_model(model, np.array([-20.0, -5.0, -0.1]))
    above = evaluate_hinge_model(model, np.array([100.1, 150.0, 400.0]))
    assert np.allclose(below, model.coss[0])
    assert np.allclose(above, model.coss[-1])
    assert np.all(above > 0.0), "extrapolation must never produce a non-positive capacitance"


def test_charge_is_continuous_so_capacitance_has_no_staircase_jumps():
    """The retired PWL failure was C DISCONTINUOUS (linear Q). C must be continuous here:
    that is the whole reason this form is preferred over a Qoss table()."""
    v, c = _junction_curve()
    model = build_adaptive_hinge_model(v, c, max_rel_error=0.02)

    grid = np.linspace(0.0, 100.0, 20001)
    cc = evaluate_hinge_model(model, grid)
    steps = np.abs(np.diff(cc))
    # no single grid step may jump more than a small fraction of the local value
    assert np.max(steps / np.maximum(cc[:-1], 1e-9)) < 0.01


# --- known-bad calibration: the guards must actually fire -------------------------------


def test_non_monotone_input_is_detected_and_refused():
    v = np.linspace(0.0, 100.0, 400)
    c = 500.0 - 3.0 * v + 0.05 * v ** 2        # dips then RISES: unphysical for a junction cap
    c[v > 60] += 200.0                          # make the rise unmistakable
    model = build_adaptive_hinge_model(v, c, max_rel_error=0.02)

    assert not model.monotone, "a curve that rises with reverse bias was reported as monotone"
    with pytest.raises(ValueError, match="not monotone"):
        spice_hinge_charge("bad_part", model)


def test_unmet_error_target_is_refused_rather_than_emitted():
    v, c = _junction_curve()
    starved = build_adaptive_hinge_model(v, c, max_rel_error=1e-6, max_knots=4)

    assert not starved.meets_target
    assert starved.achieved_max_rel_error > 1e-6
    with pytest.raises(ValueError, match="accuracy contract"):
        spice_hinge_charge("starved_part", starved)


def test_a_good_model_does_emit():
    """Complement to the refusals: the emitter must not be trivially always-refusing."""
    v, c = _junction_curve()
    model = build_adaptive_hinge_model(v, c, max_rel_error=0.02)
    text = spice_hinge_charge("IPP050N10NF2S", model, drain="dd", source="ss")

    assert "B_COSS_IPP050N10NF2S dd ss" in text
    assert "ddt(qoss_IPP050N10NF2S(V(dd,ss)))" in text
    assert re.search(r"\.func qoss_IPP050N10NF2S\(x\)", text)


def test_hinge_terms_reconstruct_the_knot_capacitances():
    v, c = _junction_curve()
    model = build_adaptive_hinge_model(v, c, max_rel_error=0.02)
    v0, c0, terms = hinge_charge_terms(model)

    for vk, ck in zip(model.vds, model.coss):
        got = c0 + sum(s * max(vk - vb, 0.0) for vb, s in terms)
        assert got == pytest.approx(ck, rel=1e-9, abs=1e-9)


def test_degenerate_inputs_raise_rather_than_return_something_usable():
    with pytest.raises(ValueError):
        build_adaptive_hinge_model(np.array([1.0]), np.array([10.0]))
    with pytest.raises(ValueError):
        build_adaptive_hinge_model(*_junction_curve(), max_rel_error=0.0)
    with pytest.raises(ValueError):
        build_adaptive_hinge_model(*_junction_curve(), max_knots=1)
